### PR TITLE
Python 3 compatibility

### LINKED ISSUE #3: Shipping a python3 version that doesn't work.
```
pip3 install functionfs
python3 -m functionfs
```

result:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/al/.local/lib/python3.5/site-packages/functionfs/__init__.py", line 367
    except IOError, exc:
```

### PR DESCRIPTION
**Pull request by ali1234**
Some changes (range and dict stuff) may be slightly less efficient. In practice this should make no difference as the lists involved are not large.

Fixes #3

### CODE REVIEW

**Comment by vpelletier** [comment]
Overall most of the changes look good. For the {x,}range and {iter,}{items,values} changes, I tend to prefer to invoke 2to3 during setup.py as these are sadly much faster on python2. But I will have to check whether they are in a critical path (sorry, long day today).

**Comment by ali1234** [comment]
Like that? (Beware, not tested.)

**Comment by ali1234** [comment]
BTW this is why I need py3...

https://github.com/ali1234/pymtpd

**Comment by vpelletier** [comment]
Released as 0.3, thanks !

I must say I wrote this as I intended to implement a CCID class device about a year ago, but had so much to do (hardware, kernel patches, this, a i2c display driver, and the CCID spec) it exhausted my interest before I could get back to implementing the actual function...

**Pull request merged**
